sudo: required

services:
- docker

language: bash

branches:
  only:
  - master

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t erikdevries/rpi-sickrage .
# run and test image
- docker run -p 8081:8081 -it --entrypoint=/usr/bin/python erikdevries/rpi-sickrage --version

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker tag erikdevries/rpi-sickrage erikdevries/rpi-sickrage:latest
    docker push erikdevries/rpi-sickrage
  fi
